dist: xenial
language: python

branches:
  only:
    - master
    - stable

matrix:
  fast_finish: true
  include:
    - python: 2.7
      script: python setup.py flake8 && python setup.py test
    - python: 3.5
      script: python setup.py flake8 && python setup.py test
    - python: 3.6
      script: python setup.py flake8 && python setup.py test
    - python: 3.7
      script: python setup.py flake8 && python setup.py test
    - python: pypy
      script: python setup.py flake8 && python setup.py test
    - python: pypy3
      script: python setup.py flake8 && python setup.py test 
